[DFS & BFS] 4월 30일
Altu-Bitu-2/Altu-Bitu-Assignment pull request #14
Opened 2022-04-29 15:03 UTC by xodms0309

#### 내용 & 질문
> 과제 제출합니다.

#### <기존 제출>
> 1697, 2667, 10026, 11725, 13422, 16234, 19538

2022-04-30 17:38 UTC, bsa0322 requested changes
p1. 안녕하세요 태은님 😊 이번 과제도 너무 잘 풀어주셨네요!! 함수화, 가독성에 대한 사소한 코멘트와 루머문제 관련해서 더 효율적인 풀이법에 대해 코멘트 남겼습니다. 
루머 문제는 수정 후, 다시 리뷰어로 호출 부탁드려요!!
코멘트가 애매하다면 질문 부탁드려요!! 수고하셨습니다~! 🥰

2022-04-30 17:38 UTC, bsa0322 commented on 4월 15일 - DFS & BFS/10026.cpp
> +	}
p2. 이 부분이 현재 정확히 2번 반복되네요! 어떻게 하면 중복 연산을 줄일 수 있을까요?

2022-04-30 17:38 UTC, bsa0322 commented on 4월 15일 - DFS & BFS/10026.cpp
> +	}
라이브러리를 사용해서 간단하게 치환을 구현해주셨네요! 아주 좋아요~~!

2022-04-30 17:38 UTC, bsa0322 commented on 4월 15일 - DFS & BFS/10026.cpp
> +		}
p3. 인덴테이션이 깊어지네요! 범위 체크 부분을 continue로 끊어도 좋을 것 같아요~!

2022-04-30 17:38 UTC, bsa0322 commented on 4월 15일 - DFS & BFS/11725.cpp
> +vector<int> v[MAX];
vector<vector<int>> 로 선언해도 메모리에서 차이는 없을 거예요! 혹시 어떻게 하셨을 때 메모리 초과 난 건지 알 수 있을까요? 🤔

2022-04-30 17:38 UTC, bsa0322 commented on 4월 15일 - DFS & BFS/11725.cpp
> +		}
p3. dfs를 활용해서 너무 잘 풀어주셨네요!! 사실 아직 튜터링에서 다루진 않았지만, tree는 visited 배열 사용 없이도 탐색이 가능해요! 트리는 각 노드마다 연결된 정점이 최대 2개일 거예요. 그렇다면 연결된 한 정점은 부모 정점이고, 다른 정점은 무조건 자식 정점이겠죠! 이 점을 활용해서 이전 정점의 값을 저장한 다음에 부모 정점과 자식 정점의 관계를 파악해보면 어떨까요? 아직 다루지 않은 부분이니 너무 추상적으로 다가오신다면 깊게 생각 안해주셔도 괜찮습니다! 😊

2022-04-30 17:38 UTC, bsa0322 commented on 4월 15일 - DFS & BFS/11725.cpp
> +	cin >> N;
p3. c++은 변수 이름은 스네이크 표기법으로 쓰는 걸 권장하고 있어요. 소문자로 작성 부탁드려요!! 😊

2022-04-30 17:38 UTC, bsa0322 commented on 4월 15일 - DFS & BFS/13422.cpp
> +		}
p2. m-1 만큼을 더 추가해주셔서 원형을 구현해 주셨네요! 지금은 메모리가 널널해서 괜찮지만, m이 엄청 커지면 메모리가 부족해질 수도 있어요! 인덱스가 돌아가는 규칙을 잘 생각하면, 추가 없이 인덱스 조정으로 원형을 구현할 수 있을 것 같아요! 😊

2022-04-30 17:38 UTC, bsa0322 commented on 4월 15일 - DFS & BFS/13422.cpp
> +		sum += v[right];
p3. 슬라이딩 윈도우를 아주 잘 구현해 주셨어요! !사소하지만 21, 22줄과 23,24 줄은 증감연산자를 활용해서 한 줄로 합칠 수 있어 보이네요! 😊

2022-04-30 17:38 UTC, bsa0322 commented on 4월 15일 - DFS & BFS/13422.cpp
> +		else return 0;
p3. c++에선 true가 정수 1과 같아요! 이 점을 활용해서 한 줄로 합칠 수 있을 것 같네요!

2022-04-30 17:38 UTC, bsa0322 commented on 4월 15일 - DFS & BFS/16234.cpp
> +			dfs(country, visited, v, nextX, nextY);
p3. 인덴테이션이 조금 깊어지네요! 연산 부분을 밖으로 빼줘서 인덴테이션을 줄이면 가독성이 높아질 것 같아요!

2022-04-30 17:38 UTC, bsa0322 commented on 4월 15일 - DFS & BFS/16234.cpp
> +				v.clear();
p3. v를 clear()해줘서 연합을 구분해 주셨네요! 해당 배열을 사용하는 부분에서 선언하면 clear() 없이 더 가독성 있는 코드가 될 것 같아요! 😊

2022-04-30 17:38 UTC, bsa0322 commented on 4월 15일 - DFS & BFS/1697.cpp
> +int cnt = 0;
p3. 해당 변수들은 모두 지역변수로 선언해도 괜찮을 것 같네요!

2022-04-30 17:38 UTC, bsa0322 commented on 4월 15일 - DFS & BFS/1697.cpp
> +	while (!q.empty()) {
p2. visited 배열을 활용하면 queue를 pair 쌍으로 넣어주지 않고 풀이가 가능해요! 다음 정점을 탐색할 때마다 시간이 1씩 증가할테니, visited 배열에 저장을 어떻게 해주면 될까요?

2022-04-30 17:38 UTC, bsa0322 commented on 4월 15일 - DFS & BFS/19538.cpp
> +		checkRumor(rumor, temp, time);
p1. 현재 bfs 탐색과 해당 시간대에 루머를 믿은 사람이 있는지 확인하는 연산을 매 time마다 진행해서 시간이 많이 소요되고 있어요! 해당 연산들은 모두 합쳐서 bfs탐색으로 해결할 수 있습니다!

먼저, 문제에서 모든 사람이 동시에 루머를 유포한다고 했지만, bfs탐색 특성상 먼저 들어간 값을 먼저 처리하기 때문에 계속 탐색을 진행하면 자연스럽게 해당 조건은 만족할 거예요! 즉 큐에 관리하고 있는 루머 유포자들이 루머를 퍼뜨리는 순서가 시간순으로 관리될 거예요! 따라서 지금처럼 연산을 분리하지 않아도 한 번에 가능합니다!

2022-04-30 17:38 UTC, bsa0322 commented on 4월 15일 - DFS & BFS/19538.cpp
> +			}
p1. 주변인의 절반이 믿는지에 대한 확인은 O(1) 연산으로도 가능합니다! 
현재 cur은 루머를 퍼뜨리는 사람이고, 해당 연산이 수행되면 next는 주변인 중 cur이 루머를 믿는 거니까 루머를 믿는 주변인이 1명 생기는 것과 같죠! 이 점을 활용해서 몇 명이 믿는지를 배열로 관리하면, 한 번에 검사를 할 수 있어요!

2022-05-03 14:05 UTC, xodms0309 commented on 4월 15일 - DFS & BFS/11725.cpp
> +vector<int> v[MAX];
그냥 `vector<vector<int>>v (n+1, vector<int> (n)) `이렇게 선언하니까 메모리초과라고 떴습니다..! 다른곳에서 문제가 생기는걸까요..

2022-05-09 09:40 UTC, bsa0322 commented on 4월 15일 - DFS & BFS/11725.cpp
> +vector<int> v[MAX];
`vector<int> v[MAX]`는 열의 크기가 0인 것과 같은데 (MAX * 0 만큼 메모리 할당) `vector<vector<int>> v(n+1, vector<int> (n))`은 열의 크기를 n으로 주신 거라 (n+1) * (n)만큼 메모리가 할당된 것과 같아요! 그런데 해당 문제는 n의 최댓값이 100,000으로 n^2의 메모리는 10^10 이 필요하게 돼죠. 보통 c++에선 2차원 배열의 메모리가 1억을 넘으면 메모리초과라고 생각해주시는 게 좋아요! 따라서 저희는 이 문제에서 인접 행렬이 아닌 인접 리스트로 그래프를 표현해주어야 하는데요! 인접리스트는 연결된 정점만 **추가**하는 것이죠. 즉, 처음 각 정점에 연결된 열의 크기는 0일 거예요. `vector<int> v[MAX]` 도 2차원 배열의 형태인데, 열의 크기를 0으로 초기화한 것과 같으니 `vector<vector<int>>` 형태로는 크기 선언을 어떻게 해주어야 인접 리스트로 표현이 가능할까요? 😊

2022-05-09 09:50 UTC, bsa0322 approved these changes
코멘트 늦어서 너무 죄송합니다!! ㅜㅜ 
 
수정해주신 부분 모두 확인했습니다. 제가 말씀드린 부분을 다 너무 잘 캐치해주셨어요! 아주 좋아요~! 다음 과제 시에도 변수 이름은 스네이크 표기법 적용해서 소문자로 해주는 부분 주의해주시면 좋을 것 같아요! 수고하셨습니다 🥰🥰 머지해주세요~!!

2022-05-14 07:13 UTC, merged